//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProjelerim
    {
        public int ID { get; set; }
        public string ProjeAdi { get; set; }
        public string Kategori { get; set; }
        public string Teknolojiler { get; set; }
        public Nullable<int> Yil { get; set; }
    }
}
